### ISSUE TITLE
json format always handled like text

### ISSUE THREAD

**Issue by adrai** [logzio/logzio_aws_serverless#17]
How do I have to log the messages in a node.js lambda function so the shipper will handle it as json?

currently when I `console.log(logObj)` this will land in the cloudwatch and logz.io logs:

`2018-08-15T07:37:07.085Z	02af8f7c-a05e-11e8-acf8-1d43011671d3	{ version: 'dev',  .... }`

**Comment by idohalevi** [comment]
@adrai 
Hi, did you set `FORMAT` in the environment variables to json?

**Comment by adrai** [comment]
yes

**Comment by adrai** [comment]
tried both JSON and json

**Comment by idohalevi** [comment]
@adrai 
I understand that, but to make it easier to debug can you please print `log` at the start of `_parse_cloudwatch_log` function and add here the lambda logs? also can you please add here example of `something`

**Comment by adrai** [comment]
added:

```python
def _parse_cloudwatch_log(log, aws_logs_data, log_type):
    logger.info(log)
    logger.info(aws_logs_data)
    logger.info(log_type)
    ...
```

```
START RequestId: a4d8c212-a065-11e8-941f-fd00dc6e0803 Version: $LATEST
[INFO]	2018-08-15T08:31:45.314Z	a4d8c212-a065-11e8-941f-fd00dc6e0803	About to send 3 logs
[INFO]	2018-08-15T08:31:45.314Z	a4d8c212-a065-11e8-941f-fd00dc6e0803	{u'timestamp': 1534321889927, u'message': u"2018-08-15T08:31:29.909Z\t9bb0db5c-a065-11e8-8516-e37b4fbe3830\t{ version: 'dev',\n method: 'GET',\n url: '/api/project/e1f5d1-cd68fc/data?t=1534321889793',\n message: 'dev | --> called GET /api/project/046a3d29-e80f-4e68-bcbe-e1f5d1cd68fc/apikeys?t=1534321889793' }\n", u'id': u'34216521519789976523760966640015262083967775527055327232'}
[INFO]	2018-08-15T08:31:45.314Z	a4d8c212-a065-11e8-941f-fd00dc6e0803	{'invoked_function_arn': 'arn:aws:lambda:eu-west-1:837167996656:function:logz-shipper', u'logStream': u'2018/08/15/[780]35e469bfdfb645e7afaec944c0009748', u'messageType': u'DATA_MESSAGE', u'logEvents': [{u'timestamp': 1534321889927, u'message': u"2018-08-15T08:31:29.909Z\t9bb0db5c-a065-11e8-8516-e37b4fbe3830\t{ version: 'dev',\n method: 'GET',\n url: '/api/project/e1f5d1-cd68fc/data?t=1534321889793',\n message: 'dev | --> called GET /api/project/e1f5d1-cd68fc/data?t=1534321889793' }\n", u'id': u'34216521519789976523760966640015262083967775527055327232'}, {u'timestamp': 1534321890113, u'message': u'END RequestId: 9bb0db5c-a065-11e8-8516-e37b4fbe3830\n', u'id': u'34216521523937915130687662544340905682680370767167684609'}, {u'timestamp': 1534321890113, u'message': u'REPORT RequestId: 9bb0db5c-a065-11e8-8516-e37b4fbe3830\tDuration: 214.01 ms\tBilled Duration: 300 ms \tMemory Size: 256 MB\tMax Memory Used: 62 MB\t\n', u'id': u'34216521523937915130687662544340905682680370767167684610'}], u'owner': u'837167996656', u'subscriptionFilters': [u'my-app'], 'function_version': '$LATEST', u'logGroup': u'/aws/lambda/my-app'}
[INFO]	2018-08-15T08:31:45.315Z	a4d8c212-a065-11e8-941f-fd00dc6e0803	nodejs
```

**Comment by idohalevi** [comment]
@adrai 
Thanks, it looks like something in the way you log things into cloudwatch. What is your logging flow?

**Comment by adrai** [comment]
In the lambda function I just `console.log()` that’s all. https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-logging.html

**Comment by adrai** [comment]
Do you need more information?

**Comment by idohalevi** [comment]
@adrai 
The message field is not a valid json and that's why the lambda can't parse it. I think it's not related to this lambda implementation so I'm going to close this issue.

**Comment by adrai** [comment]
Have you seen the stackoverflow link?

What solution do you propose?

is this logz.io shipper not compatible with a standard lambda function with node.js runtime?

**Comment by adrai** [comment]
fyi: fixed it like this: https://github.com/locize/cloudwatch-logs-shipper-lambda/commit/db7a33592c50756f408bb017184398826b239322

**Comment by idohalevi** [comment]
@adrai 
I will have to dig into that, you can always fork this repo and send us PR. In addition, you might want to use https://github.com/logzio/logzio-nodejs instead for a quick fix

**Comment by idohalevi** [comment]
@adrai 
new version should fix it
