### ISSUE TITLE
Error when loading shipper into Lambda

### ISSUE THREAD

**Issue by jackjohnsonontrac** [logzio/logzio_aws_serverless#19]
When loading shipper into lambda and following the guide as described, the following error is recieved when tested, and the logs aren't being pulled through as expected:

{
  "errorMessage": "Unable to import module 'lambda_function'"
}

START RequestId: e1cd6cb4-d3a9-11e8-b091-fb68b51def34 Version: $LATEST
Unable to import module 'lambda_function': No module named shipper

END RequestId: e1cd6cb4-d3a9-11e8-b091-fb68b51def34
REPORT RequestId: e1cd6cb4-d3a9-11e8-b091-fb68b51def34	Duration: 0.96 ms	Billed Duration: 100 ms 	Memory Size: 512 MB	Max Memory Used: 18 MB

**Comment by idohalevi** [comment]
@jackjohnsonontrac 
The zipping instructions are not updated because of the structure changes. Can you 'cd' into cloudwatch folder and try 'mkdir dist; cp -r ../shipper dist/ && cp src/lambda_function.py dist/ && cd dist/ && zip logzio-kinesis shipper/* lambda_function.py' . 
I will update the readme soon :)

**Comment by jackjohnsonontrac** [comment]
@idohalevi 
Thanks, works a treat now!

**Comment by LennartKloppenburg** [comment]
Alternatively, you can edit line 6 in [lambda_shipper.py](https://github.com/logzio/logzio_aws_serverless/blob/master/cloudwatch/src/lambda_function.py) in the AWS Lambda Management Console:
`from shipper.shipper import LogzioShipper` to `from shipper import LogzioShipper`
for a 'quick and dirty' fix.

**Comment by idohalevi** [comment]
@LennartKloppenburg Exactly! thanks

**Comment by LennartKloppenburg** [comment]
@mlaccetti It looks like the original fix should also work. What's exactly going wrong?

**Comment by mlaccetti** [comment]
I got the ole `Unable to import module 'lambda_function'` message. Changing the import made it go away. Saw the zip file had both Python scripts in it, so unsure why the module wanted to be loaded differently.
