### ISSUE TITLE
Ability to enrich the CloudWatch logs with custom properties

### ISSUE THREAD

**Issue by joaoasrosa** [logzio/logzio_aws_serverless#23]
A useful feature for the lambda is the ability to enrich the logs with custom metrics. 
A use case is the usage of multiple AWS accounts for the different environments (dev, test, UAT, production), but the AWS services at the time of logging are not aware of it. 

When we ship the logs to Logz.io, it will be handy to add custom properties, such as `environment: testing`, which will make the querying process easier.

As an implementation, the lambda could leverage the variables, which are transformed into environment variables at runtime. It could be implemented as a single variable: `properties_to_enrich: environment=testing; foo=bar`; which will produce properties called `environment` with value `testing` and `foo` with value `bar`.

**Comment by idohalevi** [comment]
@joaoasrosa 
I like the idea and will add it to my todo list. It should be an easy fix but I can't give you an estimation when I will get to this. How urgent you feel it is to you or your company?

**Comment by joaoasrosa** [comment]
@idohalevi thanks for the reply. At the moment is not a showstopper, because we are using structure logging (`Serilog`), and we use ambient context. However, for the logs of AWS (outside of our apps), we do not have it (for instance, the start and end messages from a lambda execution). 
With this feature, we will be able to segment it. 

If I have time on the next 3 weeks, I will try to contribute with a PR. :)

**Comment by joaoasrosa** [comment]
@idohalevi 
Please let me know if I fail any code convention. It is the first time in the Python world.

**Comment by idohalevi** [comment]
#25

**Comment by idohalevi** [comment]
#25
