### ISSUE TITLE
Cloudwatch logs parsing issue

### ISSUE THREAD

**Issue by sam26880** [logzio/logzio_aws_serverless#40]
I believe there might be an error here when you're parsing the AWS Lambda logs

You have this on line number **58** in **lambda_function** code

```
if len(message_parts) == 3:
            log['@timestamp'] = message_parts[0]
            log['requestID'] = message_parts[1]
            log['message'] = message_parts[2]
```

which I think should be

```
if len(message_parts) == 4:
            log['@timestamp'] = message_parts[0]
            log['requestID'] = message_parts[1]
            log['logLevel'] = message_parts[2]
            log['message'] = message_parts[3]
```

I also think that you were trying to ignore the lines in AWS Lambda logs that start with START, END, & REPORT but they're still getting through.

**Comment by idohalevi** [comment]
@sam26880 what language are you using?

**Comment by sam26880** [comment]
Not sure I understand. I believe the code on this site is Python. Isn't it? I'm not really a python guy but I sort of tried to figure it out based on what was there.

**Comment by idohalevi** [comment]
@sam26880 Sorry for not being clear enough. The logs you're trying to ship are lambda logs? if so what code language you use in the lambda?

**Comment by sam26880** [comment]
yes..Lambda logs. I use NodeJS for my serverless functions. I even tested the changed I proposed above and it seems to be working. Only by doing this, I'm getting the actual Log Level. The code that was there before wasn't getting the log level correctly. Please double check what I'm proposing and verify it works for you as well.

**Comment by idohalevi** [comment]
@sam26880 Thank you for letting us know about this issue. I found what causes it. AWS Lambda has a different log format for each language. I was testing it only on [Python](https://docs.aws.amazon.com/lambda/latest/dg/python-logging.html) and never on [NodeJS](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-logging.html). You can see in the links that the format of each language is different. I'll see how we can have a more generic solution

**Comment by sam26880** [comment]
Please let me know when you plan to have this updated so that I can keep my version updated with latest changes

**Comment by idohalevi** [comment]
@sam26880 we will close this issue with a reference to the PR that fixed it

**Comment by ronish31** [comment]
Issue is fixed.
https://github.com/logzio/logzio_aws_serverless/pull/42
