### ISSUE TITLE
Releases and tags

### ISSUE THREAD

**Issue by roni-frantchi** [logzio/logzio_aws_serverless#45]
Hey.  
Could you guys maybe create `tag`s for released version?  
Also, ideally you could have release artifacts that are would be more 'turn key', rather than us having to copy files around before zipping.  
It makes it pretty cumbersome to consume these as IaC.  

Any improvement here would be great. For us, a serverless framework plugin would be ideal.  

Thanks

**Comment by mirii1994** [comment]
Closing this issue, as the cloudwatch & kinesis solutions are deprecated. If it's still needed for the Amplify solution, please open a new issue.
