### ISSUE TITLE
JS logs containing [ and ] are failing to parse

### ISSUE THREAD

**Issue by ShlomiAltostra** [logzio/logzio_aws_serverless#50]
When logging from JS code and the message contains `[` and `]` (such as when logging JSON that contains arrays) the log message is not being parsed nor its JSON content.

Repro:
Create a JS lambda with the following code:

```js
module.exports.handler = async (event, context) => {
  console.log('Just a message')
  console.log(JSON.stringify({
    message: 'just a JSON message'
  }))
  console.log(JSON.stringify({
    message: 'A message and array',
    array: ['with', 'data'],
  }))
  console.log(`Message with [brackets]`)

  return {
    statusCode: 200
  }
}
```

And the messages that contain brackets aren't being parsed:
![image](https://user-images.githubusercontent.com/57314279/97799266-a579cf00-1c35-11eb-83f0-398240a37fb2.png)

Compare 
![image](https://user-images.githubusercontent.com/57314279/97799244-81b68900-1c35-11eb-8c82-1ec2199c8492.png)
 with 
![image](https://user-images.githubusercontent.com/57314279/97799257-9135d200-1c35-11eb-99b1-057908af693c.png)

**Comment by Doron-Bargo** [comment]
Hi @ShlomiAltostra 
We managed to reproduce your issue.
We trying to figure why it's happening . Will let you know shortly

**Comment by Doron-Bargo** [comment]
Hi @ShlomiAltostra we found the bug the cause this issue and we are working on a fix

**Comment by Doron-Bargo** [comment]
https://github.com/logzio/logzio_aws_serverless/pull/51

**Comment by Doron-Bargo** [comment]
Hi @ShlomiAltostra 
We released a new version to support this issue.
This version is only for python 3 as python2 is depreacted
Please check if it solve your problem and close this issue
Thanks

**Comment by ShlomiAltostra** [comment]
@Doron-Bargo 
Tested
The above function is fixed, by logging a message that contains `error`, `info` etc in bracket would fail as before (maybe split the message on '\t' before the check?)
![image](https://user-images.githubusercontent.com/57314279/98472332-02a7ee80-21fb-11eb-9959-60efa44ca1f3.png)


Anyway, as our issue is fixed, I'm closing
