### ISSUE TITLE
shipper.py's GzipLogRequest produces non-POSIX-compliant lines

### ISSUE THREAD

**Issue by nuno-silva** [logzio/logzio_aws_serverless#52]
[POSIX defines a Line](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) as:
> 3.206 Line
A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

However, in [shipper.py](https://github.com/logzio/logzio_aws_serverless/blob/c1cf511ed9e291ec3fa9b76ed9352a0a8c51dbca/python3/shipper/shipper.py), a `\n` is added only between "lines" and not after every line. For example:

```
line1\nline2\nline3
```

This is not POSIX compliant and increases the complexity of the code (requires a counter and an additional if):

https://github.com/logzio/logzio_aws_serverless/blob/c1cf511ed9e291ec3fa9b76ed9352a0a8c51dbca/python3/shipper/shipper.py#L48-L50

Assuming logz processes POSIX-compliant lines, the body of `write(self, log)` should be changed to something like

```python
self._writer.write(bytes(log+"\n", 'utf-8'))
self._logs_counter += 1
```

The counter needs to be kept for `__len__(self)` only.

**Comment by mirii1994** [comment]
Closing this issue, as the cloudwatch & kinesis solutions are deprecated. If it's still needed for the Amplify solution, please open a new issue.
