### ISSUE TITLE
shipper.py's GzipLogRequest does not close underlying stream

### ISSUE THREAD

**Issue by nuno-silva** [logzio/logzio_aws_serverless#53]
The `GzipLogRequest` class is using a `gzip.GzipFile` class backed by an `io.BytesIO` stream:

https://github.com/logzio/logzio_aws_serverless/blob/c1cf511ed9e291ec3fa9b76ed9352a0a8c51dbca/python3/shipper/shipper.py#L38-L39

The `GzipLogRequest.close()` method closes the `GzipFile`:
https://github.com/logzio/logzio_aws_serverless/blob/c1cf511ed9e291ec3fa9b76ed9352a0a8c51dbca/python3/shipper/shipper.py#L69-L70

However, as per [class gzip.GzipFile](https://docs.python.org/3/library/gzip.html#gzip.GzipFile):
> Calling a GzipFile object’s close() method does not close fileobj

So I believe the `GzipLogRequest.close()` should also call `self._logs.close()`.

**Comment by mirii1994** [comment]
Closing this issue, as the cloudwatch & kinesis solutions are deprecated. If it's still needed for the Amplify solution, please open a new issue.
