### ISSUE TITLE
Deploy via Serverless Application Repo ?

### ISSUE THREAD

**Issue by tblakers** [logzio/logzio_aws_serverless#57]
Would it be possible to push an official version to SAR?

This makes it super-easy to integrate into Cloudformation, because everyone can then just reference it directly in an existing template, which saves doing a deploy across all your accounts and regions.

If not, I'll probably just do a local build and push to private SAR.

**Comment by mirii1994** [comment]
Closing this issue, as the cloudwatch & kinesis solutions are deprecated.
