### ISSUE TITLE
GzipLogRequest fails with 413 (Too large upload size)

### ISSUE THREAD

**Issue by rangagopalan** [logzio/logzio_aws_serverless#61]
The GzipLogRequest does not increment the `self._decompress_size` variable  and if there are a large number of records in the batch it can cause the upload to fail with a 413 https://docs.logz.io/shipping/log-sources/json-uploads.html#request-entity-too-large.

You can fix this by updating the  `write` method (https://github.com/logzio/logzio_aws_serverless/blob/master/python3/shipper/shipper.py#L49) of the GzipLogRequest class.

```
    def write(self, log):
        bytes_to_write = bytes("\n" + log, 'utf-8') if self._logs_counter else bytes(log, 'utf-8')
        self._writer.write(bytes_to_write)
        self._decompress_size += sys.getsizeof(bytes_to_write)
        self._logs_counter += 1
```

**Comment by mirii1994** [comment]
Closing this issue, as the cloudwatch & kinesis solutions are deprecated. If it's still needed for the Amplify solution, please open a new issue.
