### ISSUE TITLE
Cloudwatch log-shipper process exits with Exception on list JSON message

### ISSUE THREAD

**Issue by hitotito** [logzio/logzio_aws_serverless#62]
# Problem
When cloudwatch's log message contains JSON list type message, it will throw (raise) the following exception:
```
[ERROR] AttributeError: 'list' object has no attribute 'items' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 142, in lambda_handler     if _parse_cloudwatch_log(log, additional_data):   File "/var/task/lambda_function.py", line 92, in _parse_cloudwatch_log     _parse_to_json(log)   File "/var/task/lambda_function.py", line 77, in _parse_to_json     for key, value in json_object.items():
```

https://github.com/logzio/logzio_aws_serverless/blob/master/python3/cloudwatch/src/lambda_function.py#L72-L80
This exception is not caught since the exception handler is only looking for specific Error types.

# Analysis
This can only happen for any valid JSON payload that is not an object.  I think that's only List (`[...]`).

Since Error is not caught, the process will exit thus all `aws_logs_data` that was consumed is likely not processed / shipped.  This causes an even bigger blast radius if the user of the log-shipper is shipping logs from multiple logGroups.

## Opinion
IMHO, the try/except block should be handled at `_parse_cloud_watch_log()`, which seems to be the method that handles each log. 
https://github.com/logzio/logzio_aws_serverless/blob/master/python3/cloudwatch/src/lambda_function.py#L144-L149
https://github.com/logzio/logzio_aws_serverless/blob/master/python3/cloudwatch/src/lambda_function.py#L83-L93

 I also think list type should be parsed correctly, but since I'm aware of how the ingestion side process the data, this might be much harder than I imagine.

**Comment by mirii1994** [comment]
Hi @hitotito ,
Thanks for notifying us about this issue. We released a fix.
Please try the updated version, and let us know if this solves your problem :)

**Comment by Doron-Bargo** [comment]
Hi @hitotito is this still relevant?

**Comment by hitotito** [comment]
Sorry about the delayed response.  This issue is resolved with the latest change.  Thank you!
