### ISSUE TITLE
Lambda sometimes timeouts after 60 seconds

### ISSUE THREAD

**Issue by ryan65** [logzio/logzio_aws_serverless#71]
Hi 
We are  using the shipper.py code in our lambda with a timeout of 60 seconds to ship logs to lambda.
We see on very very rare occassions that 60 seconds (or more) pass , between the time the request is sent without returning from the request , and then our lambda timed out.
We dont see any retry logs , so it looks like the first call to logzio doesnt return after 60 seconds , in the shipper.py
 request = urllib.request.Request(self._logzio_url, data=self._logs.bytes(),
                                             headers=self._logs.http_headers())
            return urllib.request.urlopen(request)

The specific amount of data sent in this specific lambda call which  timed out was relatively small so it not a size issue.
Questions: 
1. do you expect on rare occassions the logzio server to respond more than 60 seconds ???
2. Why didnt you add a max timeout to the request call ?

Any help would be great .
Thanks.

**Comment by mirii1994** [comment]
Closing this issue, as the cloudwatch & kinesis solutions are deprecated.
