### ISSUE TITLE
Cloudwatch log shipper doesn't work with lambda insights

### ISSUE THREAD

**Issue by ls-jacob-lawrence** [logzio/logzio_aws_serverless#73]
We use the cloudwatch shipper.
We enabled lambda insights.
We started getting a lot of `logzio-index-failure` in our logs.
The index-failed-reason is
```
{"type":"mapper_parsing_exception","reason":"failed to parse field [@timestamp] of type [date] in document with id 'REDACTED'. Preview of field's value: 'EXTENSION'","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse date field [EXTENSION] with format [strict_d...
```

The reason the "@timestamp" field is incorrectly populated seems due to [this code](https://github.com/logzio/logzio_aws_serverless/blob/eb6486def64ec78854155c2701cc5443a1486f94/python3/cloudwatch/src/lambda_function.py#L71)

Lambda insights logs seem to use [a different format](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html) from normal logs
```
EXTENSION	Name: cloudwatch_lambda_agent	State: Ready	Events: [INVOKE,SHUTDOWN]
```

These logs don't seem very valuable, so I'd imagine they should never be forwarded to logzio in the first place.

**Comment by Doron-Bargo** [comment]
Hi @ls-jacob-lawrence thanks for raising this issue. 
We will add support to Lambda insight format
